language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - "4.0.2"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
    - haxelib git chrome-extension https://github.com/tong/chrome.extension
    - haxelib dev chrome-app .

script:
  - haxe haxedoc.hxml
