language: haxe

os:
  - linux

haxe:
  - "3.2.1"
  - development

script:
  - haxelib git chrome-extension https://github.com/tong/chrome.extension
  - haxelib git chrome-app https://github.com/tong/chrome.app
  - haxe haxedoc.hxml
